# ===============================================
# Configuración Institucional y de la Aplicación
# ===============================================
app.institucion.nombre=Universidad Icesi
app.institucion.departamento=Ingeniería de Sistemas
app.sistema.version=2.0-SpringCore
app.sistema.ambiente=PRODUCCION

# ===============================================
# Parámetros Financieros y de Matrícula
# ===============================================
app.matricula.max-creditos=20
app.matricula.costo-credito=480000
app.matricula.descuento-beca=0.15
app.matricula.habilitada=true
app.matricula.email-contacto=matriculas@icesi.edu.co